[project]
name = "scratchlink-fakehub"
version = "0.0.1"
dependencies = [
    "websockets>=11.0"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "python-semantic-release"
]